server:
  port: 4002
eureka:
  client: 
    service-url:
      defaultZone: http://server7001.com:7001/eureka
  instance:
    instance-id: configserver-3344
    prefer-ip-address: true
spring:
  application:
    name: config-server7001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HeNanFei/ConfigTest2.git
#          username: 2531700373@qq.com
#          password: Zjjwan1314
          search-paths:
            - ConfigTest23
          default-label: master
