
server:
  port: 3355
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://server7001.com:7001/eureka
  instance:
    instance-id: configclient-3355
    prefer-ip-address: true
spring:
  application:
    name: 传统美德本特克
  cloud:
    config:
      uri: http://localhost:3344
      profile: dev
      label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"


